/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j2YoGVeV4Wn
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"


export function LandingPage() {
  return (
    <>
      <section className="bg-yellow-300 py-12 w-full">
        <div className="container mx-auto px-4">
          <div className="flex flex-col items-center justify-center">
            <div className="mb-8">
              <img
                alt="Noon Affiliate Program Logo"
                className="rounded-lg mt-16"
                height={163}
                src="/noon-logo.png"
                style={{
                  aspectRatio: "363/163",
                  objectFit: "cover",
                }}
                width={363}
              />
            </div>
            <div className="text-center mb-8">
              <h2
                className="text-3xl font-bold mb-2"
              >
                برنامج التسويق بالعمولة نون
              </h2>

              <h2
                className="text-3xl font-bold mb-8"
              >
                Noon Affiliate Marketing Program
                <br></br>
                <span className="text-base">السعودية 🇸🇦 الإمارات 🇦🇪</span>
              </h2>

              <div className="text-8xl font-bold text-gray-700 mb-4">
                عمولات تصل حتى
              </div>
              <div className="flex flex-row gap-8 justify-center">
                <div className="text-8xl font-bold text-gray-700 mb-4">ريال/درهم</div>
                <div className="text-8xl font-bold text-gray-700 mb-4">40</div>
              </div>
              <div className="text-8xl font-bold text-gray-700 mb-4">
                على كل طلب
              </div>
            </div>
            <div className="flex flex-row justify-center gap-4">
              <Button className="bg-gray-900 text-white rounded-md px-6 py-2 hover:bg-gray-700 transition-colors duration-200">
                اشتراك
              </Button>
              <Button className="bg-gray-900 text-white rounded-md px-6 py-2 hover:bg-gray-700 transition-colors duration-200">
                تسجيل الدخول
              </Button>

            </div>

          </div>
        </div>
      </section>


      <section className="py-12 w-full">
        <div className="container mx-auto px-4 mt-16">
          <h2
            className="text-3xl font-bold  text-center mt-4"
          >
            تفاصيل البرنامج
          </h2>
          <h2
            className="text-6xl font-bold mb-8 text-center "
          >
            عمولة لك و خصومات للمشتري
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-32">
            <Card>
              <CardHeader>
                <CardTitle className="font-bold">عمولة مبيعات 1% مقابل كل طلب </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-lg">برنامج نون للتسويق بالعمولة، سيمكنك من الربح مقابل كل طلب يتم من خلالك.</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="font-bold">عنوان البطاقة</CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-lg">هذه جملة عربية وهمية لتعبئة المساحة</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="font-bold">عنوان البطاقة</CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-lg">هذه جملة عربية وهمية لتعبئة المساحة</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </>



  )
}
